#!/usr/bin/env python3
"""Renders state/config.json's keybinds into hypr/keybinds.lua, a Hyprland
Lua config fragment required by hypr/nyxdots.lua (Hyprland's config format
on this system is native Lua — hl.bind(...), hl.dsp.*, not the old
hyprlang .conf syntax). Run this after any keybind edit (the Settings app
does this automatically) and before booting the nested test session.

Seeds state/config.json from config/default.json on first run.
"""
import json
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STATE_CONFIG = REPO_ROOT / "state" / "config.json"
DEFAULT_CONFIG = REPO_ROOT / "config" / "default.json"
OUT_FILE = REPO_ROOT / "hypr" / "keybinds.lua"
SHELL_DIR = REPO_ROOT / "shell"


def lua_str(s):
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


# action name -> Lua dispatcher expression string, for plain hl.bind(...).
# "launcher"/"settings" are handled separately since they talk to the
# running shell over IPC.
DISPATCH_ACTIONS = {
    "terminal": lambda: "hl.dsp.exec_cmd(\"foot\")",
    "browser": lambda: "hl.dsp.exec_cmd(\"firefox\")",
    "fileExplorer": lambda: "hl.dsp.exec_cmd(\"thunar\")",
    # Rofi, not the old QML launcher — see rofi/nyxdots.rasi.template and
    # scripts/generate-rofi-theme.py for the themed config it reads.
    "launcher": lambda: "hl.dsp.exec_cmd("
        + lua_str(f'rofi -show drun -theme "{REPO_ROOT}/state/rofi-theme.rasi"')
        + ")",
    "close": lambda: "hl.dsp.window.close()",
    "fullscreen": lambda: 'hl.dsp.window.fullscreen({ mode = "fullscreen" })',
    "floating": lambda: "hl.dsp.window.float()",
    "screenshot": lambda: "hl.dsp.exec_cmd("
        + lua_str(
            "mkdir -p ~/Pictures/Screenshots && "
            'grim -g "$(slurp)" ~/Pictures/Screenshots/nyxdots-$(date +%s).png'
        )
        + ")",
    "lock": lambda: 'hl.dsp.exec_cmd("loginctl lock-session")',
    "nextWorkspace": lambda: 'hl.dsp.focus({ workspace = "e+1" })',
    "prevWorkspace": lambda: 'hl.dsp.focus({ workspace = "e-1" })',
}

# "launcher" taps SUPER on release (not held), so it doesn't fight
# SUPER+num workspace binds.
RELEASE_BIND_ACTIONS = {"launcher"}

IPC_ACTIONS = {
    "settings": "settings",
}


def ensure_state_config():
    STATE_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    if not STATE_CONFIG.exists():
        shutil.copy(DEFAULT_CONFIG, STATE_CONFIG)


def split_combo(raw):
    raw = raw.strip()
    if "," in raw:
        mods, key = raw.split(",", 1)
        return mods.strip(), key.strip()
    return "", raw


def lua_combo(raw):
    mods, key = split_combo(raw)
    parts = [p for p in mods.split(" ") if p] if mods else []
    parts.append(key)
    return " + ".join(parts)


def bind_line(combo, dispatch_expr, opts=None):
    opts = opts or {}
    args = [lua_str(lua_combo(combo)), dispatch_expr]
    if opts:
        fields = ", ".join(f"{k} = {v}" for k, v in opts.items())
        args.append("{ " + fields + " }")
    return f"hl.bind({', '.join(args)})"


def ipc_exec_expr(ipc_target):
    cmd = f'qs -p "{SHELL_DIR}" ipc call {ipc_target} toggle'
    return f"hl.dsp.exec_cmd({lua_str(cmd)})"


def main():
    ensure_state_config()
    config = json.loads(STATE_CONFIG.read_text())
    keybinds = config.get("keybinds", {})
    custom = config.get("customKeybinds", [])
    scale = config.get("display", {}).get("scale", 1.0)

    lines = [
        "-- GENERATED by scripts/generate-keybinds.py — do not edit by hand.",
        "-- Edit keybinds/display from the NyxDots Settings app, or state/config.json",
        "-- directly, then re-run this script (or let Settings do it for you).",
        "",
        f'hl.monitor({{ output = "", mode = "preferred", position = "auto", scale = {scale} }})',
        "",
    ]

    for action, dispatch_fn in DISPATCH_ACTIONS.items():
        combo = keybinds.get(action)
        if not combo:
            continue
        opts = {"release": "true"} if action in RELEASE_BIND_ACTIONS else {}
        lines.append(bind_line(combo, dispatch_fn(), opts))

    for action, ipc_target in IPC_ACTIONS.items():
        combo = keybinds.get(action)
        if not combo:
            continue
        opts = {"release": "true"} if action in RELEASE_BIND_ACTIONS else {}
        lines.append(bind_line(combo, ipc_exec_expr(ipc_target), opts))

    lines.append("")
    lines.append("-- Workspaces (fixed convention, not remapped from Settings)")
    for i in range(1, 10):
        lines.append(bind_line(f"SUPER, {i}", f"hl.dsp.focus({{ workspace = {i} }})"))
        lines.append(bind_line(f"SUPER SHIFT, {i}", f"hl.dsp.window.move({{ workspace = {i} }})"))

    if custom:
        lines.append("")
        lines.append("-- Custom keybinds")
        for bind in custom:
            combo = bind.get("combo", "")
            exec_cmd = bind.get("exec", "")
            if combo and exec_cmd:
                lines.append(bind_line(combo, f"hl.dsp.exec_cmd({lua_str(exec_cmd)})"))

    lines.append("")
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines))
    print(f"wrote {OUT_FILE}")


if __name__ == "__main__":
    sys.exit(main())
